### ISSUE TITLE
Create a repository that uses environment variables

### ISSUE THREAD

**Issue by deanmarano** [mgsnova/feature#54]
Hi there! We're currently enjoying this gem, and I was looking to contribute. I wanted to see if what I was thinking makes sense.

In our YAML files, most of our lines look like this: `stripe: <%= ENV['STRIPE_ENABLED'] == "true" %>`. I was wondering if there would be any interest/objection in having an EnvRepository that uses environment variables as the source of feature flagging. If so, I'll create a PR with that functionality.

Thanks for your contributions!

**Comment by will3216** [comment]
I'm not the repository owner by any means, but I've used this gem for awhile now and I think that makes sense!

**Comment by javidjamae** [comment]
Environment variables are usually loaded only during application start. If I’m not mistaken, this strategy would force you to restart your system to change the toggle state, which takes away a huge benefit of using feature toggles. I would just put the state in Redis or a DB, if I were you.

**Comment by will3216** [comment]
Hey @javidjamae! To Javid's point, that's in line with how we use this gem, but I think that makes a few assumptions about the use-case which may not apply to every application, it assumes...
* The application is stateful; if the application does not use a data store of any kind yaml or environment variable configuration may be beneficial
* The features are used in a way where they can be changed dynamically, eg, if I have a feature toggle that states the application should use sidekiq vs resque the application will need to be restarted otherwise things will get out of whack
* These are being used in a steady-state application. If this is being used in a non-steady state application, such as a batch processing application; the value of dynamically changing the values is gone completely
* Operational tooling doesn't already exist for controlling the app with environment variables. If app configuration is handled exclusively with environment variables, new tools will need to be developed to support toggling and maintaining DB-backed feature toggles

An env based repository is inline with the yaml based one, so if it makes sense with your use-case I don't see the harm in adding it.

**Comment by deanmarano** [comment]
No longer working on this project, so this is not needed.
